name: Jest Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Lấy code từ GitHub
        uses: actions/checkout@v4

      - name: Cài đặt Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Cài đặt thư viện
        run: npm install

      - name: Chạy Jest Test
        run: npm test
